"""new fields in user model

Revision ID: 187418fab6eb
Revises: c06bcd06af88
Create Date: 2018-06-26 17:32:37.866352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187418fab6eb'
down_revision = 'c06bcd06af88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
